name: "PWskill"

on:
    push:
        branches:
            - master
            - development

            pull_request:
                branches:
                    - master
                    
jobs:
PWskill:
if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
        - name: "Hello Macha"
          run: echo "Hello Macha"

        PWskill pull_request:
        if: github.event_name == 'pull_request'
            runs-on: ubuntu-latest
            steps:
                - name: "Hello Macha"
                  run: echo "Hello Macha"
