name: "hello macha"

on:
    push:
        branches:
            - master
            - production

jobs:
    hello_macha:
        runs-on: ubuntu-latest
        steps:
            - name: "Hello Macha"
              run: echo "Hello Macha"

            - name: "print current date and time"
              run: date